### ISSUE TITLE
Warning when using this plugin

### ISSUE THREAD

**Issue by shmuelfomberg** [SineSwiper/Dist-Zilla-PluginBundle-Prereqs#1]
I have added this plugin to my dist.ini file, and got the following warnings on build:

Use of uninitialized value $distro in hash element at C:/strawberry/perl/site/li
b/Dist/Zilla/Plugin/PrereqsClean.pm line 169.
Use of uninitialized value $distro in hash element at C:/strawberry/perl/site/li
b/Dist/Zilla/Plugin/PrereqsClean.pm line 170.
Use of uninitialized value $distro in hash element at C:/strawberry/perl/site/li
b/Dist/Zilla/Plugin/PrereqsClean.pm line 171.

**Comment by SineSwiper** [comment]
Looks like a minor issue, but this will be fixed in the next release.

**Comment by shmuelfomberg** [comment]
thanks
