### ISSUE TITLE
PrereqsClean seems to be removing Test::Fixme from prereqs

### ISSUE THREAD

**Issue by robrwo** [SineSwiper/Dist-Zilla-PluginBundle-Prereqs#4]
Using a dist.ini with the following options (in that order):

``` ini
[@Basic]      ; (actually filtered, but not removing ExtraTests)
[AutoPrereqs]
[CPANFile]
[PrereqsClean]
```

I've added an `xt/release/no-fixme.t` file with the following:

``` perl
use Test::Fixme;
run_tests(...);
```

It does not add (and will remove) Test::Fixme from the cpanfile.

Note that I've not (yet) tested the Test::Fixme plugin.

**Comment by robrwo** [comment]
Note: Dist::Zilla::Plugin::Test::Fixme has issues with the default configuration that make it unusable in my  circumstances.

**Comment by SineSwiper** [comment]
PrereqsClean has quite a bit of debug output when turned on.  What does the PrereqsClean section give you when you run `dzil test -v`?

**Comment by robrwo** [comment]
The output doesn't say anything about Test::Fixme.

Looking it over further, I think the issue is with AutoPrereqs, since removing that doesn't fix the issue.
